version: "3.10"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: todolist_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgres

  migrations:
    image: chickyd0t/todolist:version-1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    command: python manage.py migrate

  api:
    image: chickyd0t/todolist:version-1
    ports:
      - 80:80
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.env:/app/.env

  front:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - 80:80
    depends_on:
      - api